# Generated by Django 4.1.5 on 2023-02-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_priority_priorityrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorityrecord',
            name='week',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priorityrecord',
            name='member_email',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
