# Generated by Django 4.1.5 on 2023-02-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0007_remove_member_id_alter_member_email'),
        ('main', '0004_alter_priorityrecord_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='member_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registering.member'),
        ),
    ]
