# Generated by Django 4.1.5 on 2023-01-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255)),
                ('chinese_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=255)),
                ('student_id', models.PositiveSmallIntegerField()),
                ('membership_years_duration', models.PositiveSmallIntegerField()),
                ('membership_start_date', models.DateField()),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
