# Generated by Django 4.1.5 on 2023-01-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='password1',
            new_name='password',
        ),
    ]
