# Generated by Django 4.1.5 on 2023-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0002_rename_password1_member_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='chinese_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_years_duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='paid',
            field=models.BooleanField(null=True),
        ),
    ]
