# Generated by Django 4.1.5 on 2023-01-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0003_alter_member_chinese_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
