# Generated by Django 4.1.5 on 2023-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0004_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=0),
        ),
    ]
