# Generated by Django 4.1.5 on 2023-02-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registering', '0005_member_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
